import { VerticalBox, HorizontalBox } from "std-widgets.slint";

component SvgButton inherits Rectangle {
    in property source <=> i.source;
    in property<bool> flip: false;
    in property<length> x_offset: 0px;
    callback clicked();

    width: self.height;
    height: 48px;
    border-radius: self.width;
    i := Image {
        x: (parent.width - self.width) / 2 + x_offset;
        y: (parent.height - self.height) / 2;
        width: 40%;
        height: 40%;
        colorize: #fffc;
        transform-rotation: flip ? 180deg : 0deg;
    }
    ta := TouchArea {
        clicked => {
            root.clicked();
        }
    }
    states [
        down when ta.pressed: {
            background: #fff2;
            in-out {
                animate background { duration: 50ms; }
            }
        }
        active when !ta.has-hover: {
            background: transparent;
        }
        active-hover when ta.has-hover: {
            background: #fff4;
            in {
                animate background { duration: 500ms; easing: ease-out-quint; }
            }
            out {
                animate background { duration: 500ms; easing: ease-in; }
            }
        }
    ]
}

export component CanvasWindow inherits Window {
    in property<float> horizontal_padding_ratio: 0.1;
    in property<float> top_padding_ratio: 0.1;
    in property<float> bottom_padding_ratio: 0.1;
    out property<duration> tick: animation-tick();
    in property<image> art_image;
    in property<string> track_artist: "Artist";
    in property<string> track_title: "Title";
    in property<string> track_album: "Album";
    in property<bool> playing: false;
    callback previous();
    callback play_pause();
    callback next();

    title: "Beskope";
    background: transparent;
    preferred-width: 1600px;
    preferred-height: 800px;

    VerticalBox {
        x: parent.width * horizontal_padding_ratio;
        y: parent.height * top_padding_ratio;
        width: parent.width - self.x * 2;
        height: parent.height - parent.height * (bottom_padding_ratio + top_padding_ratio);
        cache-rendering-hint: true;

        Rectangle {}

        Rectangle {
            Rectangle {
                width: cover.width;
                height: cover.height;
                drop-shadow-blur: 20px;
                drop-shadow-color: black;
            }
            cover := Image {
                source: art_image;
                image-fit: preserve;
                vertical-alignment: bottom;
            }
        }

        Rectangle { height: 10px; }

        VerticalBox {
            Text {
                text: track_artist;
                font-size: 20px;
                horizontal-alignment: center;
                color: white;
            }
            Text {
                text: track_title;
                font-size: 20px;
                font-weight: 800;
                horizontal-alignment: center;
                color: white;
            }
            Text {
                text: track_album;
                font-size: 20px;
                horizontal-alignment: center;
                color: #aaa;
            }
        }

        HorizontalBox {
            Rectangle {}
            SvgButton {
                source: @image-url("icons/first-track-multimedia-button-svgrepo-com.svg");
                clicked => previous();
            }
            SvgButton {
                source: playing
                    ? @image-url("icons/pause-two-lines-svgrepo-com.svg")
                    : @image-url("icons/play-arrow-svgrepo-com.svg");
                // The play icon looks off-center due to its shape, move it a bit.
                x_offset: playing ? 0px : 2px;
                clicked => play_pause();
            }
            SvgButton {
                source: @image-url("icons/first-track-multimedia-button-svgrepo-com.svg");
                flip: true;
                clicked => next();
            }
            Rectangle {}
        }
    }
}
