import { AboutSlint, VerticalBox, Slider, Button, HorizontalBox } from "std-widgets.slint";

export component CanvasWindow inherits Window {
    in property<float> horizontal_padding_ratio: 0.1;
    in property<float> top_padding_ratio: 0.1;
    in property<float> bottom_padding_ratio: 0.1;
    out property<duration> tick: animation-tick();
    in property<image> art_image;
    in property<string> track_artist: "Artist";
    in property<string> track_title: "Title";
    in property<string> track_album: "Album";
    in property<string> play_button_text: "⏯";
    callback previous();
    callback play_pause();
    callback next();

    background: transparent;
    preferred-width: 800px;
    preferred-height: 800px;

    VerticalBox {
        x: parent.width * horizontal_padding_ratio;
        y: parent.height * top_padding_ratio;
        width: parent.width - self.x * 2;
        height: parent.height - parent.height * (bottom_padding_ratio + top_padding_ratio);
        Rectangle {}

        cache-rendering-hint: true;
        Image {
            source: art_image;
        }

        Text {
            text: track_artist;
            font-size: 20px;
            horizontal-alignment: center;
        }
        Text {
            text: track_title;
            font-size: 20px;
            font-weight: 800;
            horizontal-alignment: center;
        }
        Text {
            text: track_album;
            font-size: 20px;
            horizontal-alignment: center;
            color: #222
            ;
        }

        HorizontalBox {
            Button {
                text: "⏮";
                clicked => previous();
            }
            Button {
                text: play_button_text;
                clicked => play_pause();
            }
            Button {
                text: "⏭";
                clicked => next();
            }
        }

        Rectangle {}
    }
}
