import { VerticalBox, Slider, HorizontalBox, GroupBox, TabWidget, ComboBox, LineEdit, GridBox, AboutSlint } from "std-widgets.slint";

enum RenderChannels {
    Both,
    Left,
}

enum PanelLayout {
    TwoPanels,
    SingleTop,
    SingleBottom,
}

enum PanelLayer {
    Background,
    AboveWindows,
    AboveFullscreenWindows,
}

export global Configuration {
    callback changed();

    in-out property<color> fill_color: Colors.rgba(32, 32, 32, 0.8);
    in-out property<color> stroke_color: Colors.rgba(205, 205, 205, 0.8);
}

export global PanelConfiguration {
    callback channels_changed(RenderChannels);
    callback layout_changed(PanelLayout);
    callback layer_changed(PanelLayer);

    in-out property<RenderChannels> channels: RenderChannels.Both;
    in-out property<PanelLayout> layout: PanelLayout.TwoPanels;
    in-out property<PanelLayer> layer: PanelLayer.AboveWindows;
}

component LabeledSlider {
    in-out property<float> value <=> slider.value;
    in property<string> label <=> text.text;
    in property<float> minimum <=> slider.minimum;
    in property<float> maximum <=> slider.maximum;
    callback changed(float);
    HorizontalBox {
        text := Text {
            vertical-alignment: TextVerticalAlignment.center;
        }
        slider := Slider {
            changed(value) => { changed(value) }
        }
        Text {
            width: 10%;
            text: round(value*100)/100;
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.left;
        }
    }
}

component HsvColorSelection inherits GroupBox {
    in-out property<float> h <=> h_slider.value;
    in-out property<float> s <=> s_slider.value;
    in-out property<float> v <=> v_slider.value;
    in-out property<float> a <=> a_slider.value;
    callback changed();
    VerticalBox {
        h_slider := LabeledSlider {
            label: "H";
            maximum: 359.999;
            changed(value) => { changed() }
        }
        s_slider := LabeledSlider {
            label: "S";
            maximum: 1.0;
            changed(value) => { changed() }
        }
        v_slider := LabeledSlider {
            label: "V";
            maximum: 1.0;
            changed(value) => { changed() }
        }
        a_slider := LabeledSlider {
            label: "A";
            maximum: 1.0;
            changed(value) => { changed() }
        }
    }
}

export component ConfigurationWindow inherits Window {
    function update_configuration() {
        Configuration.fill_color = Colors.hsv(fill_color.h, fill_color.s, fill_color.v, fill_color.a);
        Configuration.stroke_color = Colors.hsv(stroke_color.h, stroke_color.s, stroke_color.v, stroke_color.a);
        Configuration.changed();
    }

    preferred-width: 800px;
    preferred-height: 600px;

    TabWidget {
        Tab {
            title: "General";
            GridBox {
                Row {
                    Text {
                        text: "Channels per window/panel";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    channels_cb := ComboBox {
                        enabled: layout_cb.current-value != "Two panels (one on each side of the screen)";
                        model: [
                            "Both left and right",
                            "Only left",
                        ];
                        current-index: PanelConfiguration.channels == RenderChannels.Both ? 0 : 1;
                        selected(current-value) => {
                            if (self.current-index == 0) {
                                PanelConfiguration.channels = RenderChannels.Both;
                            } else {
                                PanelConfiguration.channels = RenderChannels.Left;
                            }
                            PanelConfiguration.channels_changed(PanelConfiguration.channels);
                        }
                    }
                }
                Row {
                    Text {
                        text: "Panel layout";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    layout_cb := ComboBox {
                        model: [
                            "Two panels (one on each side of the screen)",
                            "Single panel at the top",
                            "Single panel at the bottom",
                        ];
                        current-index: PanelConfiguration.layout == PanelLayout.TwoPanels
                            ? 0 
                            : PanelConfiguration.layout == PanelLayout.SingleTop
                                ? 1
                                : 2;
                        selected(current-value) => {
                            if (self.current-index == 0) {
                                channels_cb.enabled = false;
                                channels_cb.current-index = 0;
                            } else {
                                channels_cb.enabled = true;
                            }

                            if (self.current-index == 0) {
                                PanelConfiguration.layout = PanelLayout.TwoPanels;
                            } else if (self.current-index == 1) {
                                PanelConfiguration.layout = PanelLayout.SingleTop;
                            } else {
                                PanelConfiguration.layout = PanelLayout.SingleBottom;
                            }
                            PanelConfiguration.layout_changed(PanelConfiguration.layout);
                        }
                    }
                }
                Row {
                    Text {
                        text: "Panel Layer";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    layer_cb := ComboBox {
                        model: [
                            "Background",
                            "Above windows",
                            "Above full-screen windows",
                        ];
                        current-index: PanelConfiguration.layer == PanelLayer.Background
                            ? 0
                            : PanelConfiguration.layer == PanelLayer.AboveWindows
                                ? 1
                                : 2;
                        selected(current-value) => {
                            if (self.current-index == 0) {
                                PanelConfiguration.layer = PanelLayer.Background;
                            } else if (self.current-index == 1) {
                                PanelConfiguration.layer = PanelLayer.AboveWindows;
                            } else {
                                PanelConfiguration.layer = PanelLayer.AboveFullscreenWindows;
                            }
                            PanelConfiguration.layer_changed(PanelConfiguration.layer);
                        }
                    }
                }
                Rectangle { }
            }
        }
        Tab {
            title: "Color";
            VerticalBox {
                fill_color := HsvColorSelection {
                    changed => { update_configuration(); }
                    title: "Fill";
                    h: Configuration.fill_color.to_hsv().hue;
                    s: Configuration.fill_color.to_hsv().saturation;
                    v: Configuration.fill_color.to_hsv().value;
                    a: Configuration.fill_color.to_hsv().alpha;
                }
                stroke_color := HsvColorSelection {
                    title: "Stroke";
                    changed => { update_configuration(); }
                    h: Configuration.stroke_color.to_hsv().hue;
                    s: Configuration.stroke_color.to_hsv().saturation;
                    v: Configuration.stroke_color.to_hsv().value;
                    a: Configuration.stroke_color.to_hsv().alpha;
                }
            }
        }
    }
}
